version: '3.8'
services:
    db:
        env_file:
            - .env
        container_name: '${MYSQL_CONTAINER_NAME}'
        image: 'mariadb:${MARIADB_VERSION}'
        ports:
            - ${MYSQL_HOST_PORT}:3306
        volumes:
            - './db/mysql:/var/lib/mysql'
    wordpress:
        env_file:
            - .env
        build:
            context: .
            dockerfile: wordpress.dockerfile
            args:
                WORDPRESS_VERSION: ${WORDPRESS_VERSION}
                PHP_VERSION: ${PHP_VERSION}
                SSL_SUBJECT: '/C=NA/ST=NA/L=NA/CN=NA/O=NA/OU=IT/'
                XDEBUG_VERSION: ${XDEBUG_VERSION}
                XDEBUG_PORT: ${XDEBUG_PORT}
                WORDPRESS_WORKDIR_CONTAINER: ${WORDPRESS_WORKDIR_CONTAINER}
                WORDPRESS_CONTAINER_NAME: ${WORDPRESS_CONTAINER_NAME}
        image: '${WORDPRESS_CONTAINER_NAME}'
        container_name: '${WORDPRESS_CONTAINER_NAME}'
        depends_on:
            - db
        ports:
            - ${WORDPRESS_HOST_PORT}:80
            - ${WORDPRESS_HOST_SSL_PORT}:443
        volumes:
            - './${WORDPRESS_WORKDIR}:${WORDPRESS_WORKDIR_CONTAINER}'
